### ISSUE TITLE
[fluent] compatibility

### ISSUE THREAD

**Issue by theMisteryDE** [vertyco/vrt-cogs#105]
Hi there, I used your cog as a welcome addition to Trusty's translate cog.
Sadly, some updates ago you added the "translate" command, which is already used by Trustys,
My Users wanna keep his Flag Emoji Translation, while I wanna keep the Auto-Translate channels.
Since this is the younger cog, any chances that you make it compatible?

**Comment by vertyco** [comment]
There is not an intuitive alias for translate IMO so i'll be closing this, sorry.
