### ISSUE TITLE
[LevelUp] [Feature] Import AmariBot Levels

### ISSUE THREAD

**Issue by CptDinosaur** [vertyco/vrt-cogs#114]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to import levels from AmariBot
It'd need the user to set an API Key

The API is documented here
https://litochee.gitbook.io/amaribot/api/api
A python library exists here
https://amaripy.readthedocs.io/en/latest/

**Describe the solution you'd like**
A lvlset admin importamari command

**Describe alternatives you've considered**
I could write my own script to create a .json file to import, using the amari api

**Comment by vertyco** [comment]
I am willing to take a look into this but you would need to provide me an API key and guild id to test with. You can DM me on discord with the key and guild id, my discord username is `vertyco`

**Comment by CptDinosaur** [comment]
Awaiting an API key now

**Comment by vertyco** [comment]
Closing this as completed
