### ISSUE TITLE
[Tickets] Bot restart requires reload

### ISSUE THREAD

**Issue by EternalllZM** [vertyco/vrt-cogs#116]
**Describe the bug**
For some reason after starting the bot or a restart of it, the tickets cog "drops" the buttons leading to "This interaction failed" error message until the cog is reloaded.

**To Reproduce**
1. Restart bot
2. Ticket buttons will not work
3. Reload tickets cog
4. Buttons are fixed

**Expected behavior**
The cog should load and acknowledge ticket buttons without requiring a reload.

**Screenshots**
N/A

**Additional context**
Unfortunately I do not see any errors or logs. Our group has created a scheduled task to reload the cog every so often to prevent this.

**Comment by vertyco** [comment]
I need to know which buttons you're referring to. the close button? open buttons? join buttons? or all of them? which ones have you tested?

**Comment by EternalllZM** [comment]
Apologies, the panel buttons that open a modal or ticket.

**Comment by vertyco** [comment]
try to do some testing with things now

**Comment by vertyco** [comment]
closing this as resolved
