### ISSUE TITLE
[LevelUp] Experience Decay

### ISSUE THREAD

**Issue by EternalllZM** [vertyco/vrt-cogs#117]
**Is your feature request related to a problem? Please describe.**
Not really a problem. However, some people become inactive within the server and if your server is setup to allow privileged permissions after certain levels, leaving accounts dormant at high levels is sort of risky. If they get hacked and you allowed exceptions through automod or similar, it can wreak havoc.

**Describe the solution you'd like**
A configurable experience decay. This could be either a flat rate or a range. There could also be role exclusions from this decay. This means that every 24 hours or so, a user would lose say 10xp.

**Describe alternatives you've considered**
N/A

**Additional context**
This might not be possible, considering autoremove would have to be enabled in order for them to lose their highest role if it "collects" the roles. Otherwise, this is practically useless and suggestion is null as the original "problem" is not solved.

**Comment by vertyco** [comment]
After some lengthy consideration i dont know if i will have the time to implement this, we would need to track every user's last active time, but also define what counts as being active. in addition to that it would require another task loop to iterate through all the users and check which would be more overhead, so i'll be closing this for now.
