### ISSUE TITLE
[LevelUp] Intialize ignores prestige for hierarchy rank roles

### ISSUE THREAD

**Issue by EternalllZM** [vertyco/vrt-cogs#118]
**Describe the bug**
`[p]lvlset roles initialize` ignores prestige. This means if you do a complete reprovision (remove roles via autoremove intialize, then disable autoremove and rerun), it will only provide the roles of the current level on that prestige.

**To Reproduce**
1. Gain roles up to prestiging
2. Prestige, level roles are not removed
3. Autoremove roles
4. lvlset intiailize
5. Roles are now gone except prestige
6. Run initialize again
7. Now only the rank you are at on the prestige is re-obtained, rather than all the roles leading up to prestige

**Expected behavior**
While this is how prestige works in games and such, this isn't how levelup is setup to work, as the autoremove for prestige is only for the prestige levels, not the rank levels. Therefore, it should re-add all the rank roles if the user is prestiged.

**Screenshots**

**Additional context**
The process of doing this can be automated via other means, but it would be better if initialize counts for this if this is how the prestige process is going to work.

**Comment by vertyco** [comment]
This should be fixed in version 3.5.2
