### ISSUE TITLE
TICKETS SYSTEM RESTART BUG

### ISSUE THREAD

**Issue by CreatorX8** [vertyco/vrt-cogs#120]
**TICKETS SYSTEM**

**Is your feature request related to a problem? Please describe.**
When the bot is restarted and has opened tickets displays error for the LogView. 
![image](https://github.com/vertyco/vrt-cogs/assets/90335627/720b28c4-4a4a-4ac7-835b-fecf737b3de0)

**Describe the solution you'd like**
To fix the issue you have to add one line of code in tickets/views.py
Line 625: self.join_ticket.custom_id = str(channel.id)
![image](https://github.com/vertyco/vrt-cogs/assets/90335627/fe23c4ca-8f09-48a8-be1e-ad496caae621)

This fix the error!

Sincerely,
Creator X

**Comment by vertyco** [comment]
thank you for reporting, this bug has been patched with v2.1.14
