### ISSUE TITLE
[LevelUp] Custom Leveling Algorithms

### ISSUE THREAD

**Issue by SeaswimmerTheFsh** [vertyco/vrt-cogs#125]
**Is your feature request related to a problem? Please describe.**
Currently, LevelUp doesn't support custom leveling algorithms like the ones the [Polaris bot](https://gdcolon.com/polaris/) uses.
<details>
  <summary>Here's an example of what I mean:</summary>
<img src="https://media.seaswimmer.cc/ULorMw9/direct.png" alt="img">
</details>
I'm trying to migrate to LevelUp from Polaris and it'd be nice if I didn't have to recalculate what levels to give certain reward roles and such at with a different algorithm.

**Describe the solution you'd like**
Add a way to use cubic functions such as the ones Polaris uses.

**Describe alternatives you've considered**
I don't know of any alternatives that would implement something similar?

**Comment by vertyco** [comment]
I don't think i'll be implementing this as the current quadratic algorithm is already customizable, allowing cubic leveling algos and more would introduce more complexity that i currently do not have the time to write
