### ISSUE TITLE
[Fluent] Translation doesn't work

### ISSUE THREAD

**Issue by Nogooduser** [vertyco/vrt-cogs#13]
The cog lets me set channels just fine, but translation has stopped working entirely.

The logs indicate a problem with the googletrans library. Is there something that can be done to fix it or is it just a matter of waiting for an upstream fix?

**Comment by vertyco** [comment]
The cog silently dismisses issues when the api is acting up. Since its a free api sometimes it goes down. Also make sure your current version of googletrans is version "3.1.0a0"

**Comment by Nogooduser** [comment]
It doesn't even show googletrans is installed when I run ``pip show googletrans`` in my venv. But the cog worked before so I'm not sure what's up with that.

In any case, I tried installing googletrans 3.1.0a0 in my venv using pip but that didn't fix the cog (it also caused some conflicts with Red since it downgraded a couple of its dependencies). 

Am I supposed to install googletrans in some other way?

**Comment by vertyco** [comment]
Activate your venv with the bot off.
Do "pip uninstall googletrans"
Then do "pip install googletrans==3.1.0a0"
That worked for me

**Comment by Nogooduser** [comment]
That seems to have fixed it, thanks.

However I did get the following package incompatibility errors after installing googletrans

![](https://kyot.me/ez8hb8widc37.png)

Will red bot still be fine despite those?

**Comment by vertyco** [comment]
Not 100% sure but i believe those are unrelated to the fluent cog. I could be wrong. However you can always do "pip --upgrade PackageName" for any dependencies that are out of date

**Comment by Nogooduser** [comment]
They are related to fluent because both chardet and idna are used by httpx, which is in turn used by googletrans, and in turn by fluent.

If I upgrade both so that redbot gives conflict errors, httpx (installed by googletrans) says it can't use them because it's asking for an older version. And if I then upgrade httpx so it can use those newer packages, googletrans says it can't use httpx, and I can't progress past that since upgrading googletrans isn't possible.

Upgrading chardet and idna and leaving httpx with conflicts still seems to allow the cog to function, which I suppose is fine (though it seems to be a lot laggier). But upgrading httpx makes the cog completely stop functioning (can't load at all), likely because googletrans can't use it.

So I suppose the only way to use the cog is with that package conflict with httpx. I don't necessarily mind the conflict since it's not a red dependency, but I guess worth keeping in mind for fluent.

I'll close the issue now since I got the cog running again. Thank you for the help!

**Comment by vertyco** [comment]
Interesting, ill try different versions and see if there is a working one compatible with those libs
