### ISSUE TITLE
Add Claiming to ticket system

### ISSUE THREAD

**Issue by cj2tech** [vertyco/vrt-cogs#130]
**Is your feature request related to a problem? Please describe.** no

**Describe the solution you'd like** I'd like for there be to be a claim button inside the ticket that is pressable by the support role. Once click it will print a message in the ticket stating which user has claimed it
![image](https://github.com/vertyco/vrt-cogs/assets/9431091/e5e4124f-93c3-42a9-9957-17267fb2b767)
![image](https://github.com/vertyco/vrt-cogs/assets/9431091/ba8dd3c8-86c6-4a81-9b15-9b89df7757c4)

**Describe alternatives you've considered** 
using ticketsbot.net but I'd prefer to use a self-hosted/managed solution

**Additional context**

**Comment by vertyco** [comment]
The closest existing thing to this is the ability to set a max join amount for the log channel's "join" button via the `[p]tset maxclaims` command, however I have no plans to implement the specific ability to claim tickets.
