### ISSUE TITLE
[Tickets] Interaction Failed (on a new thread) - Rare appearance. 

### ISSUE THREAD

**Issue by Skyridr** [vertyco/vrt-cogs#133]
So I've set up the basics of the ticket system to test it out. Managed to create a single thread, closed it just fine. But when I attempted to open up a second one, the interaction failed with this as traceback:

```py
Traceback (most recent call last):
  File "/home/koala/koala/cogs/CogManager/cogs/tickets/views.py", line 241, in callback
    await self.create_ticket(interaction)
  File "/home/koala/koala/cogs/CogManager/cogs/tickets/views.py", line 539, in create_ticket
    await interaction.response.send_message(embed=em, ephemeral=True)
  File "/home/koala/koala/lib/python3.11/site-packages/discord/interactions.py", line 801, in send_message
    await adapter.create_interaction_response(
  File "/home/koala/koala/lib/python3.11/site-packages/discord/webhook/async_.py", line 219, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction
```

It did create the thread, but was unable to close it.

![image](https://github.com/vertyco/vrt-cogs/assets/6794064/a4d57c43-62eb-4746-a002-e1f24d99c155)

This only happened once by the way. All other ticket threads created just fine and was unable to repeat it afterwards. But I wanted to report the issue nonetheless.

**Comment by Skyridr** [comment]
I have noticed however, the second time this happened it might be due to #134  

> [2023-09-10 09:22:30] [WARNING] discord.http: We are being rate limited. PUT https://discord.com/api/v10/channels/1150360636488957981/thread-members/550133475248701460 responded with 429. Retrying in 3.28 seconds.
> [2023-09-10 09:22:36] [WARNING] discord.http: We are being rate limited. PUT https://discord.com/api/v10/channels/1150360636488957981/thread-members/1048785017570078830 responded with 429. Retrying in 2.82 seconds.
> [2023-09-10 09:22:41] [WARNING] discord.http: We are being rate limited. PUT https://discord.com/api/v10/channels/1150360636488957981/thread-members/900412294981369897 responded with 429. Retrying in 3.14 seconds.
> [2023-09-10 09:22:46] [ERROR] red.vrt.supportview: Failed to create ticket in Club Koala: 404 Not Found (error code: 10062): Unknown interaction

You can see that at 09:22:41 bot is being rate limited. and at 09:22:46 unknown interaction error popped up with the same traceback as the original post.

**Comment by vertyco** [comment]
I've added a fallback to try sending the message to a the channel, and if that errors to itll silently fail but still should still open the ticket and operate normally
