### ISSUE TITLE
[Tickets] Adding too many users from supportrole causes rate limitation

### ISSUE THREAD

**Issue by Skyridr** [vertyco/vrt-cogs#134]
It appears that when a support role has many users (24 users in our case), rate limitation is being applied of altering (in our case thread) permissions.

> [2023-09-10 09:22:30] [WARNING] discord.http: We are being rate limited. PUT https://discord.com/api/v10/channels/1150360636488957981/thread-members/550133475248701460 responded with 429. Retrying in 3.28 seconds.
> [2023-09-10 09:22:36] [WARNING] discord.http: We are being rate limited. PUT https://discord.com/api/v10/channels/1150360636488957981/thread-members/1048785017570078830 responded with 429. Retrying in 2.82 seconds.
> [2023-09-10 09:22:41] [WARNING] discord.http: We are being rate limited. PUT https://discord.com/api/v10/channels/1150360636488957981/thread-members/900412294981369897 responded with 429. Retrying in 3.14 seconds.

We have been using a different role now though with less users in them, but wanted to report it.

**Comment by vertyco** [comment]
Unfortunately this is a limitation of thread tickets since you can't add users in bulk with a single api call. i would recommend having less support roles per panel to reduce this issue a bit.
