### ISSUE TITLE
[Tickets] Use <#thread/channelid> in Ticket Overview rather than plain text.

### ISSUE THREAD

**Issue by Skyridr** [vertyco/vrt-cogs#135]
The ticket Overview is awesome feature to have to view all open tickets. But have noticed it's using plain text. Is it possible that it's using the channel/thread ID link so you can instantly view it from the overview? 

So instead of:

.skyrider(test) 30 minutes ago - Skyrider

It would be:

<#ID>(test) 30 minutes ago - Skyrider

I do understand that it would increase the the characters a bit, but it would be much more effective.

**Comment by vertyco** [comment]
It was designed that way on purpose for thread tickets. you can now run `[p]tset overviewmention` to toggle mentioning of the channels
