### ISSUE TITLE
[cartographer] missing requirements

### ISSUE THREAD

**Issue by Technetium1** [vertyco/vrt-cogs#145]
**Describe the bug**
Doesn't load due to missing pydantic

**Cog Version**
latest

**To Reproduce**
Do fresh setup of Red, try to install and load the cog

**Expected behavior**
it to load

**Screenshots**
no

**Additional context**
https://github.com/vertyco/vrt-cogs/blob/3a8331aa5078f27b5a112d2556662e01ad5aaa9f/cartographer/info.json#L12

**Comment by vertyco** [comment]
ty for reporting, just pushed a patch for this
