### ISSUE TITLE
[Leveler] Custom text based level ups & Role notification suggestion.

### ISSUE THREAD

**Issue by Skyridr** [vertyco/vrt-cogs#148]
I really hope this suggestion can be implemented. It's a simple embed custom text where you can adjust your own level up message and the text that shows up when you gain a role as well as per image below.

![image](https://github.com/vertyco/vrt-cogs/assets/6794064/c648fb2f-e1f4-4041-b7c9-8324f33af8c4)

First one shows the text when you gain a level and a specific role. And the second image is when you gain a level without a role (normal level ups). I implemented this on Fixator's cog back in the days, so the image above isn't from your cog. I was more thinking that custom tags such as {user} {level} and {role} could be used, with user outside the embed for mention (optional)

**Comment by vertyco** [comment]
This has been requested a few other times, and is something i'm not particularly desiring to implement, but PRs are always welcome of course provided it is implemented in a way that makes sense

**Comment by vertyco** [comment]
Added with most recent commit:
`[p]lset alerts` base command

`[p]lset alerts dm`: the DM the user gets when leveling up without getting a role
`[p]lset alerts dmrole`: the DM the user gets when leveling up and getting a role

`[p]lset alerts msg`: the message sent in the channel when a user levels up without getting a role
`[p]lset alerts msgrole`: the message sent in the channel when a user levels up and gets a role

I haven't really tested this all that much so if you run into any errors just post em in my support channel.
