### ISSUE TITLE
[LevelUp] importleveler only imports users who have sent a message since the cog was loaded

### ISSUE THREAD

**Issue by blanksuspect** [vertyco/vrt-cogs#15]
I'm using aikaterna's fork of fixator's leveler cog. When I use the `importleveler` command, it only imports 2 users (my user and another user who sent a message after the cog was loaded) and nothing else. There are no errors in the log while executing the command.

**Comment by blanksuspect** [comment]
I switched to using fixator's leveler cog, which uses the same mongodb so all the data is the same. I still can only import the users who have sent messages since importing the LevelUp cog.

**Comment by vertyco** [comment]
Ill take a look at it when i get home, it may be only importing users that have an existing config with leveler, ill fix that if so

**Comment by vertyco** [comment]
Alright you can update the cog and try again now. the issue should be resolved, it now creates data for any users that dont exist yet in the levelup config. If this fixes your issue you can close this.
