### ISSUE TITLE
[Pixl] Answers are `case sesitive` when uploaded via .txt file & `showglobal` instead `useglobal`

### ISSUE THREAD

**Issue by cool-aid-man** [vertyco/vrt-cogs#154]
Hey Alex, 
I've got **two issues,** so I'm gonna specify both of them into one issue (*saving the hassle of going into another GH-issue*) :)
`i.` = Issue no 1
`ii.` = Issue no 2

**Describe the bug + Issue**
> - `i.` Noticed the answers are case-sensitive when you upload them as bulk I.e. via .txt file --> `pixlset image addglobal/add` 
> - `ii.` In `pixlset` there're `showanswer`, `showdefault`, but `useglobal` (everything starts with `show-` except one is `use-`)

The 2nd point (`ii.`) is not really an "issue" but more of  QOL thing if you wanna say! because every time you want to toggle the use of global images, you always tend to do `pixlset showglobal` spontaneously as the other commands do start with `show`. 

**To Reproduce**
> - `i.` Upload a txt file with answers being Uppercase or, uppercase & lowercase mix and that's it.
> - `ii.` Run `pixlset`

**Expected behavior**
- `i.` It should take answers in all lowercase (while uploading) no matter how the input is. (It already does if you `edit` the answer, or add it as URL and answers `pixlset image add [url] [answers]`).
 - This means it should accept user's answer in any form the user might be giving, as in: Answer, answer, ANSWER should **all** be valid (Yes! it already does **ONLY** when the answers that you had given while uploading/adding the images, are all in **lowercase**). And this gets broken when you upload a file with answers with different formatting: Answer or, ANSWER (Now it will only accept the ans either as Answer or ANSWER **not** answer when it should). 

- `ii.` `useglobal` should be renamed as `showglobal` right! to match with the rest of the commands (or, at least an alias). I have had this in mind for so long but always forget to ping you up.

**Screenshots**
![image](https://github.com/vertyco/vrt-cogs/assets/84676543/57a0a7d7-f889-45cb-8cd8-cb5fa2b387b5)
![image](https://github.com/vertyco/vrt-cogs/assets/84676543/101a9cdc-f6f2-426e-b131-6511447e7635)
![image](https://github.com/vertyco/vrt-cogs/assets/84676543/12b7451e-cd4a-4974-8a1c-5864b451af61)

**Additional context**
I love cog haha & so as our users :) thanks to you! (i mean i do love all of you cogs; tickets, pixl, levelup *tho pixl is more fun stressing & heart-pounding yk ;)* ) 
As always **thank you**

**Comment by vertyco** [comment]
Just pushed an update, bulk adding should make everything lowercase now.

As for `useglobal` being changed to `showglobal` i disagree, but do notice the oddity, `showdefault` should be `usedefault` because `showanswer` is not similar to the other two commands aside from being a toggle. So `showdefault` is now `usedefault`
