### ISSUE TITLE
assistant: !assist endpoint [url] does not update the endpoint

### ISSUE THREAD

**Issue by twilwa** [vertyco/vrt-cogs#158]
**Describe the bug**
the assistant continues to call the openai endpoint, regardless of overwrites. overwrite confirmation message appears
**Cog Version***
Specify the version of the cog you are using.
assistant
**To Reproduce**
!assist endpoint [non-openai-url]
Endpoint overwritten!
!assist openaikey [key for Openai]
@bot , hello?
bot replies

**Expected behavior**
!assist endpoint [non-openai-url]
Endpoint overwritten!
!assist openaikey [key for Openai]
@bot , hello?
bot responds 'invalid api key'

**Screenshots**

**Additional context**
![image](https://github.com/vertyco/vrt-cogs/assets/111034762/26ec6717-ce0c-454d-9186-f61e0a1a8f3b)

**Comment by vertyco** [comment]
The api key needs to be removed if you want it to use the override

**Comment by twilwa** [comment]
if the overrided endpoint needs an api key, how would i handle that

**Comment by vertyco** [comment]
It doesn't, the cog only supports either OpenAI or self-hosted models, not other APIs that use keys.
