### ISSUE TITLE
[support] feature request for support cog

### ISSUE THREAD

**Issue by Oyplap** [vertyco/vrt-cogs#16]
Is it perhaps possible if you could add more buttons for separate ticket subjects?
For example: You have a button for reports and you have another button for bug reports and when you start one of the tickets it has a different ticket message.

And could you also add an option to add email support. The way it works is that when someone started a ticket, the configured email(s) address receive an notification that a ticket has been made.

Thanks for your time!

**Comment by vertyco** [comment]
The way the cog is written would require some major changes to add the ability to have multiple subjects. I may make it possible once the dust settles with red3.5 but there is no timeline.

As for email notifications, i have no plans to implement that as of this time
