### ISSUE TITLE
Optional bool for lvlup admin statreset confirmation

### ISSUE THREAD

**Issue by NonPlayerCharacterNPC** [vertyco/vrt-cogs#163]
**Is your feature request related to a problem? Please describe.**
I would like to be able to confirm the statreset in the same command

**Describe the solution you'd like**
prefixlvlset admin statreset [y/n]
prefixlvlset admin statreset [true/false]

**Comment by NonPlayerCharacterNPC** [comment]
p.s. this is not urgent and not really that crucial to be honest, it's not really a problem, just makes it more convenient, thanks for your time :)

**Comment by vertyco** [comment]
This change has been implemented with version 3.11.10
