### ISSUE TITLE
ERROR    [red] Package loading failed

### ISSUE THREAD

**Issue by Thereaper091** [vertyco/vrt-cogs#165]
[02:08:43] ERROR    [red] Package loading failed
╭─────────────────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────────────────╮
│ /home/discord/redenv/lib/python3.9/site-packages/redbot/core/core_commands.py:188 in _load                                               │
│ ❱  188                 await bot.load_extension(spec)                                                                                    │
│ /home/discord/redenv/lib/python3.9/site-packages/redbot/core/bot.py:1680 in load_extension                                               │
│ ❱ 1680         lib = spec.loader.load_module()                                                                                           │
│ in _check_name_wrapper:529                                                                                                               │
│ in load_module:1034                                                                                                                      │
│ in load_module:859                                                                                                                       │
│ in _load_module_shim:274                                                                                                                 │
│ in _load:711                                                                                                                             │
│ in _load_unlocked:680                                                                                                                    │
│ in exec_module:855                                                                                                                       │
│ in _call_with_frames_removed:228                                                                                                         │
│ /home/discord/.local/share/Red-DiscordBot/data/music/cogs/CogManager/cogs/assistant/__init__.py:6 in <module>                            │
│ ❱  6 from .assistant import Assistant                                                                                                    │
│ /home/discord/.local/share/Red-DiscordBot/data/music/cogs/CogManager/cogs/assistant/assistant.py:15 in <module>                          │
│ ❱  15 from .abc import CompositeMetaClass                                                                                                │
│ /home/discord/.local/share/Red-DiscordBot/data/music/cogs/CogManager/cogs/assistant/abc.py:12 in <module>                                │
│ ❱  12 from .common.models import DB, GuildSettings                                                                                       │
│ /home/discord/.local/share/Red-DiscordBot/data/music/cogs/CogManager/cogs/assistant/common/models.py:77 in <module>                      │
│ ❱  77 class GuildSettings(AssistantBaseModel):                                                                                           │
│ /home/discord/.local/share/Red-DiscordBot/data/music/cogs/CogManager/cogs/assistant/common/models.py:107 in GuildSettings                │
│ ❱ 107     seed: int | None = None                                                                                                        │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by vertyco** [comment]
Issue resolved with update 5.7.11
