### ISSUE TITLE
NoNuke Guild not in cache + additional quick_link function for exportchat, tickets 

### ISSUE THREAD

**Issue by cool-aid-man** [vertyco/vrt-cogs#166]
Hey alex
The `AntiNuke` once in a while just *spamming* the console with "guild not in cache", (It's a good thing that it's fetching the info here btw) till you restart the bot or the loop starts back on. Now, I was wondering if there is a way to force cache the guilds manually! 
```py
#291 [2024-01-04 15:05:11] INFO [red.vrt.antinuke] Guild test server not in cache!
#292 [2024-01-04 15:05:11] INFO [red.vrt.antinuke] Guild test server not in cache!
#293 [2024-01-04 15:05:11] INFO [red.vrt.antinuke] Guild test server not in cache!
#294 [2024-01-04 15:05:11] INFO [red.vrt.antinuke] Guild test server not in cache!
#295 [2024-01-04 15:05:11] INFO [red.vrt.antinuke] Guild test server not in cache!
#296 [2024-01-04 15:05:11] INFO [red.vrt.antinuke] Guild test server not in cache!
```
---
One more thing is, 
for the `exportchat` command under VrtUtils since there's an additional function for both [quick link and valid link](https://github.com/mahtoid/DiscordChatExporterPy/blob/51e85d3a217a14cb9c8d9e6561ec1c62aefa405d/chat_exporter/chat_exporter.py#L139) is available, so if you could include that, **in addition**, to transcripts, would be amazing, 

- This could also be extremely helpful to view the **ticket transcripts** under `Tickets` cog along with the transcript file. 

Thanks

**Comment by vertyco** [comment]
Yeah i can do that. also just pushed an update to remove that log line

**Comment by cool-aid-man** [comment]
Awesome it will really be useful yk! I think for everyone who uses **tickets** & exportchat, being able to view the transcripts just by clicking a link 
(I'm even thinking of using the cmd to log the temporary mafia channel (yet another gaming bot - to play mafia game) chat before it gets deleted by the bot haha, super useful in many ways)

and thanks for nonuke update 👍

**Comment by vertyco** [comment]
no problem :)

**Comment by vertyco** [comment]
The view link has been included in both Tickets and VrtUtils now
