### ISSUE TITLE
[NoNuke] Multiple issues and feedbacks

### ISSUE THREAD

**Issue by cool-aid-man** [vertyco/vrt-cogs#167]
Hey Alex
Been testing NoNuke, and here are the findings,
### Issues
- `nonuke` gets triggered when the config is set to `false` - which shouldn't happen.
- Most of the time it isn't even triggering on **mod actions,** till you restart the bot a couple of times which means it's not getting injected - No error on the console. 
- For the DM that a user gets, can you remove the info on (`X events in X seconds` part), since that's something you don't want to share as the user will find a way to bypass it [..for exceeding {number} mod actions in {X} seconds]
- Sometimes it throws an error saying - it can't remove roles due to not having proper perms, when it did remove and it had perms. 
- It doesn't respect what action you pick **ONCE** an action gets registered to cog's config, for example - when the action **was** set to `strips` and then you change the action to any of `notify`/`kick`/`ban` - it will still strip the roles from the user until you **restart or reload the cog**. 

### Feedback/Suggestion
- For `nonuke overload` it would be amazing to have an option to individually select or pass the overload number for each "mod action".
So one option for kick/bans, one option for channel change, etc and you can pass different overload numbers for each one, more customizability per se.
- Punish un-whitelisted users/admins giving dangerous perms (moderation perms, manage channel/server, manage permissions, webhook perms, etc) to other members (like wick) and strip their roles **and** the bot they may have used to give the role **and** strip the roles to the user who they tried on.
- Punish un-whitelisted users/admins giving dangerous perms to ANY of the server roles.
> - `Dangerous Perms are`: __Guild__ - Manage channels, manage roles, manage webhooks, manage server, kick, ban, timeout, Mention `@everyone`, Manage Messages, Manage Emojis-stickers, Administrator ; __Channel Perms__: manage channel, manage permissions, manage webhooks, mention `@everyone`, manage messages. 
- Could we have an option where you get to select your main channels & roles & and the bot will monitor them, 
> - Main roles - are the roles that people get when they join the server so any `base role`.
> - Main channels - are the channels that possess the most threat, where people chat the most, so your main chat channel. 

The idea is to monitor and **protect** the main roles including `@everyone` from getting dangerous permissions. The same goes for `main channels` - to protect these channels' `@everyone` & main roles from getting dangerous channel permissions.
These are well-respected anti-nuke features that will make the cog way more useful than it already is. 

It's an amazing cog and has a HUGE potential to be one of THE most needed cogs so thank you for making it.

**Comment by vertyco** [comment]
The issues you have mentioned should now be fixed. the cog has been refactored to improve readability and use the audit log entry listener more efficiently. 

As for the Feedback/Suggestions, I have little interest in adding any of that right now. NoNuke was never meant to be used as training wheels for server owners, but rather just a streamlined anti-nuke cog.

**Comment by cool-aid-man** [comment]
For the suggestion part, it's ALL part of the antinuke process per se & especially since now it **already listens** to the `dangerous_perms` on `on_guild_role_update` so, I feel those would have made the cog even better but no worries if you don't feel like it, not to mention it would take some times to implement such stuff 

-------
As for the update, after testing found a couple of things, 

Since nonuke can't take action on users **who's higher** than the bot's highest role in role hierarchy (which is fine) **nor** does it send any response (in the logging channel) that - "it couldn't get triggered due to bla bla... " so
- `nonuke action` - In the help embed it should include a warning something like - 
> - `I'm unable to take action on users with roles higher than mine in the hierarchy. Therefore, please ensure that my role is positioned above all staff roles.`
(So that users can know that it's their fault that the bot didn't trigger)

2nd thing is, there's no way to know who are the whitelisted users. so, 
- `nonuke view` - could show the whitelisted users.

**Comment by vertyco** [comment]
Whitelisted users are now displayed in the view command. Also actions already show in the logs if they fail like role stripping.
