### ISSUE TITLE
[LevelUp] Levelup is not registering image/Img_link as profile background

### ISSUE THREAD

**Issue by cool-aid-man** [vertyco/vrt-cogs#168]
Hey Alex,
`LevelUp` seems to have some sort of bug in it in registering images for the `pf` command. 
> - Cog Version: `3.11.14`

**To Reproduce**
1. Take a SS of any portion of your screen, any image/image_link
2. Try to set that image as profile bg, either by uploading the image directly or using the image link.
3. **Most of the time**, the cog won't register the image, **no matter** the size/aspect ratio of the image.

I did try it with autto, and seems to be working just fine with any image or image link regardless of aspect ratio, which is very weird.
- (Image no. `1.` shows that.)

Then tried the same image (that worked on autto) with the other bot, and nope it did not register the image nor the image_link
- (Have tried in other servers **several times**, (even reloading/restarting the bot) and it's the same result - mostly test servers!)
- (Image no. `2.` `3.` shows that.)

No error on the console btw!

**Comment by vertyco** [comment]
Autto is running the same version of LevelUp, I have not been able to reproduce this issue on any of my test or prod bots and have looked into this before. Unless someone else can help out with this I doubt I will dig into it any time soon as I have no real direction to take towards solving it for you.

**Comment by cool-aid-man** [comment]
## Update
The issue is solved with the recent commit, hash being: `f026db3cd237f2fc32c8b552c3f133dbaa1d5e58`.
Tested with a couple of SS and image_links, seems to be working fine. Finally !!
Thank you
