### ISSUE TITLE
Feature: Send more than 1 message(embed) in new tickets separatelly

### ISSUE THREAD

**Issue by duduws** [vertyco/vrt-cogs#17]
@Vertyco hello sir vertyco, sorry for ping you, but can you help me add an footer and header to you support cog in the open ticket message please? and if is it possible to send 2 messages, cause when i set the ticket message he only sends 1, and i want to send 2 separetelly messages, thanks and sorry for bother you

Thanks and have a great day!
![Screenshot_5](https://user-images.githubusercontent.com/64056323/169418743-47e5c4ae-e391-4bea-b3c8-334af32c2a18.png)

**Comment by vertyco** [comment]
I will probably implement this in my dpy2 version of Support, however i am not writing any new features for the current version since dpy2 required a major rewrite of the cog

**Comment by vertyco** [comment]
This feature has been implemented in my dpy2 branch of the cog(which you can use if you are on the dev version of red) and will be merged into main when red3.5 drops
