### ISSUE TITLE
[LevelUp] Multiple Issues with levelup

### ISSUE THREAD

**Issue by cool-aid-man** [vertyco/vrt-cogs#178]
## 1st Issue:
The issue is after the recent update, hash being - `57e48dd100eb7ae03ee3d6bba87645304314b2ff` it seems the `Total Exp` part got removed from the embed. 
e.g. 
- Before 👇
![image](https://github.com/vertyco/vrt-cogs/assets/84676543/aead7610-2c42-4ea7-acb4-51e39dbea8ea)
- After 👇
![image](https://github.com/vertyco/vrt-cogs/assets/84676543/f524904f-1bda-4b41-afcb-6baac71ee518)
> - **Update**: Discord fixed the issue with embed (being pushed out to the left) & code block (that was broken before)
So, the code block can come back :)
-----
## 2nd Issue 
It's a well-known issue at this point I suppose, and you already know it, - 
The `mypf bg` with **attachment**, still doesn't seem to be recognizing the attachment **atall** and **always replies** with "Uh Oh, looks like that is not a valid URL"
> - I tried in multiple bots yet same result. 

e.g.
- Test Instance 
![image](https://github.com/vertyco/vrt-cogs/assets/84676543/1a6070d2-6d65-4d4b-9849-d384da7c6df3)
- On autto
![image](https://github.com/vertyco/vrt-cogs/assets/84676543/88c42dba-8ccf-4e7f-af4e-234468168da6)
- A complete new instance **JUST** for this test - where the cog has just been **freshly** installed
![image](https://github.com/vertyco/vrt-cogs/assets/84676543/0e1a6213-b4f8-465e-bb28-ea2d2e292da7)
> - Sometimes it also removes the previous bg (which was set before e.g. card01) gets removed when it returns "Uh Oh, looks like that is not a valid URL"

Same story with passing a **valid `image link`**
![image](https://github.com/vertyco/vrt-cogs/assets/84676543/2af277d7-9ad8-4d6a-a296-9f2f8ed8557d)
![image](https://github.com/vertyco/vrt-cogs/assets/84676543/4dd8d4e8-998b-4fb7-9b24-69dc0d32f17f)
![image](https://github.com/vertyco/vrt-cogs/assets/84676543/29f6488b-333f-4c19-bc82-5fc03365b141)

Honestly, it's been an issue for sooo long, sometimes it works sometimes it doesn't, highly unpredictable behavior, not to mention - nothing on the console, no error. 

That's all for today thank you :)

**Comment by vertyco** [comment]
Fixed with v3.15.6
