### ISSUE TITLE
[Support] Feature Request

### ISSUE THREAD

**Issue by Cool-aid-man** [vertyco/vrt-cogs#18]
### Support Cog
As of right now, the cog can log the conversations from the ticket channel as a **transcript** to a certain channel, which is great. And works just fine. 

> A request would be to have another __subcommand__, to `DM` the owner/who opened the ticket, with the **transcripts** in the form of a TXT file after **closing** the ticket.

- That makes a lot of sense since after closing the ticket, the ticket-owner loses the access to the channel.
- It'd also make everything **transparent**, in the sense of, **no** would be able to tamper with the channel content(s) (deny or edit/add/remove any comments) afterwards from the ticket channel which itself is meant to be a temporary channel.
- A **toggle** option would be great, and having an extra option to customize it would be even better.

Thank you

**Comment by vertyco** [comment]
I have plans to add this as a feature for when Red3.5 releases :)

**Comment by Cool-aid-man** [comment]
That's great! 
It's really a nice cog. 
Thank **you** :) )

**Comment by Cool-aid-man** [comment]
Closing the issue. :)
