### ISSUE TITLE
[ExtendedEconomy] Refractor the cog to accept per-server pricing system while keeping the global bank intact

### ISSUE THREAD

**Issue by cool-aid-man** [vertyco/vrt-cogs#183]
Hi Alex 
For `extendedeconomy`, When `global` bank is active, it doesn't let you add cost to a cmd without setting the `level` as global.
> e.g. `addcost insult 69 420 admin button static 2`

I feel it would be better if you could change it to accept per server system while keeping the global bank intact, as (from a bot-owner or normal user POV) you might **not want** to add cost to __every single server__ the bot is in (and only want to add the system to **certain servers**), but also want keep the "global leaderboard" (as people do look at the lb to grind more/less depending on their positions on the lb)

- By "change it" means: Having a **toggle switch**, that only the bot_owner can change to make it accept per_guild price while keeping the global bank intact, would be perfect as anyone can then make that adjustment as per their liking.
That's all

I Hope you eventually find it interesting haha to work on it soon enough!
Thanks for the amazing cogs :) (from tickets to gmail to levelup to economy - everything is great 👌)

**Comment by vertyco** [comment]
After giving it much thought I really have no desire to implement this. In my opinion it makes no sense to allow per-server prices when using a global economy as it contradicts the point of it being a global bank in the first place.
