### ISSUE TITLE
[p]mypf addfont

### ISSUE THREAD

**Issue by PBOwner** [vertyco/vrt-cogs#184]
**Describe the bug**
Whenever I try to add *any* font from *any* site, it doesn't register at all.

**Cog Version***
3.5.9

**To Reproduce**
1. Download any font
2. Run [p]mypf addfont *fontname* with attatchment
3. Restart the bot
4. Run {p}mypf font *newfontname*
5. Font doesn't show up

**Expected behavior**
Font to show up

**Additional context**
NA

**Comment by vertyco** [comment]
@PBOwner why don't you add credits back to the fork of levelup you made and then i'll consider helping you...
https://github.com/vertyco/vrt-cogs/compare/main...PBOwner:vrt-cogs:main

**Comment by PBOwner** [comment]
x_xblossomx_x

**Comment by vertyco** [comment]
fixed in the rewrite
