### ISSUE TITLE
Integrating conversions from Arcane

### ISSUE THREAD

**Issue by PBOwner** [vertyco/vrt-cogs#191]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I was wondering if there was a way you can integrate importing of xp and/or levels from the Arcane bot

**Describe alternatives you've considered**
I have been manually transferring over levels with the [p]lvlset setlevel

**Additional context**

**Comment by vertyco** [comment]
If you can provide me with  as much of the following as you can i might be able to do it.
- documentation for their api
- server ID i can use to test
- API key (if it requires one)
- the URL for the endpoint

**Comment by PBOwner** [comment]
Nevermind, They don't offer exports. I wish they did, as it would make life much easier.
