### ISSUE TITLE
Globally configured leveling type and card

### ISSUE THREAD

**Issue by PBOwner** [vertyco/vrt-cogs#192]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like the ability to be able to set a global configuration, that a guild owner can change, to which you can set globally to use embeds or generated pictures. I would also like the ability to make it so that each user can set their profile card globally too, so they don't have to set it each server, but can be changed in different servers

**Describe alternatives you've considered**

**Additional context**

**Comment by vertyco** [comment]
> I would like the ability to be able to set a global configuration, that a guild owner can change, to which you can set globally to use embeds or generated pictures.
This is setting already exists: `[p]lvlowner forceembeds`

> I would also like the ability to make it so that each user can set their profile card globally too.
LevelUp is not intended to be used this way, it was designed for per-server customization.
