### ISSUE TITLE
[VrtUtils] or, [NewCog] Feature Req: Have a cmd to Manage the new APP/Bot Emojis.

### ISSUE THREAD

**Issue by cool-aid-man** [vertyco/vrt-cogs#193]
Hi Alex,

I hope you're doing great.

### **This is a feature request that is Not related to any problems, this is a new project idea.**
> (I just thought this is amazing & you might be interested in adding this to `VrtUtils` or making it in a new cog. Hence this request.)

So, Discord woke up from sleep and thought of doing something **good** *this time* - which is adding emojis to the bot directly (instead of making private servers to upload emojis to, you can now directly upload them to the bot either via API or through the [developer portal](https://discord.com/developers/applications/{id}/emojis). This is now available to every bot developer out there.

- The current Limit is 2000 Emojis (**Two-thousand Emojis**)
- Emojis can currently be uploaded by Bot-owner(s).
- The emojis can **Only** be managed and used by the bot/app.
- Command structure can be - `<p>botemoji [add|edit|list|delete] [emoji_name] [emoji|link]`  (or `<p>appemoji ...`)
> I'm sure you've better names in mind for the cmd name, the `link` can be a valid image link ending with .png/.jpg/.gif. By default running the cmd alone `botemoji`/`appemoji` would bring up the help menu.

### API Doc Links
> - List of Application Emojis
> - Get Emoji
> - Add/Create Application Emojis
> - Edit/Modify Application Emojis 
> - Delete App Emojis

API Doc Link - https://discord.com/developers/docs/resources/emoji#list-application-emojis (the get_emoji, add, edit, and delete are on that page.)

I feel this could be a very good addition to the `VrtUtils` if possible, or as a separate cog if VrtUtils isn't the perfect place for it.

Thanks

**Comment by vertyco** [comment]
Before i check this out, what is the minimum version of dpy that supports application emojis? I glanced over the docs but didnt see any mention

**Comment by cool-aid-man** [comment]
I forgot to mention but dpy 2.4 does support this, yes. (Not entirely sure about the minimum req. tho)

I tried with this following snippet and it brought up the uploaded emojis **if** they exist (I had uploaded them to the dev. portal prior); **else** it will fetch `{'items': []}`
> `<p>eval`
> ```py
> from discord.http import Route
> kwargs = {
>     "application_id": "123456789",  # snowflake of App/Bot ID
> }
> route: Route = Route(method="GET", path="/applications/{application_id}/emojis", **kwargs)
> return await ctx.bot.http.request(route=route)
> ```

It fetched the following 👇 when emojis are present
```py

{
    'items': [
        {
            'id': '1263730117679779980', # 👈 Emoji_ID
            'name': 'coolaid', # 👈 emoji-Name
            'user': {
                'id': '776855156032798761',
                'username': 'coolaidman.',
                'avatar': '6e7241decae6769b57220d3fe8c9ff7c',
                'discriminator': '0',
                'public_flags': 4194432,
                'flags': 4194432,
                'banner': None,
                'accent_color': None,
                'global_name': 'Cool aid',
                'avatar_decoration_data': {
                    'asset': 'a_89cd524789a0c6d64d57489631c0e70e',
                    'sku_id': '1226939754578986532',
                    'expires_at': None
                },
                'banner_color': None,
                'clan': None
            },
            'roles': [],
            'require_colons': True,
            'managed': False,
            'animated': False,
            'available': True
        }
    ]
}
```

**Comment by vertyco** [comment]
alright, i've started adding the commands, might be able to push it out this evening or sunday

**Comment by cool-aid-man** [comment]
Awesome thank you, can't wait to test things out! 
:)

**Comment by vertyco** [comment]
Added with version 2.7.0
