### ISSUE TITLE
Ticket embed args aren't right

### ISSUE THREAD

**Issue by Fajardao** [vertyco/vrt-cogs#194]
**Describe the bug**
The ticket embed command only have to args, the title and the description

**Cog Version***
Latest at 19/07/2024

**To Reproduce**
Just try the default command

**Expected behavior**
Is expected, acording to the docs to be able to change to change the color and channel of the embed message

**Screenshots**
![image](https://github.com/user-attachments/assets/5b8674d3-519b-44c6-ba3f-e7df61b0e7b1)

**Comment by vertyco** [comment]
Thats because you have to include the actual text in those placeholders.

For example: `!tickets embed gold #open-a-ticket "Click the button below to open a ticket"`

For future questions about cog usage, please ask in the 3rd party support Discord for Red [Here](https://discord.gg/GET4DVk)
