### ISSUE TITLE
[NoNuke] Self updates can trigger actions

### ISSUE THREAD

**Issue by EternalllZM** [vertyco/vrt-cogs#200]
**Describe the bug**
A member updating their nickname rapidly can trigger nonuke.

**Cog Version***
1.2.0

**To Reproduce**
1. Set nonuke to trigger on `member_update`
2. Set timer to something like 60 seconds
3. Change nickname twice in time period
4. NoNuke triggers

**Expected behavior**
It shouldn't action on self updates. Furthermore, this user wasn't had no privileged roles or permissions. I am not sure this behavior is strict enough with its requirements before executing.

**Comment by vertyco** [comment]
Should be fixed with v1.2.1
