### ISSUE TITLE
[Cartographer] restoring backwards

### ISSUE THREAD

**Issue by RawrUniversal** [vertyco/vrt-cogs#201]
**Describe the bug**
I have a bug with cartographer, when restoring the roles and messages restore in backwards order, the lower roles are at the top and the the earliest messages are at the top.

**Cog Version***
Newest

**To Reproduce**
1. Backup a server
2. Restore the server
3. see they are backwards

**Expected behavior**
It should be in the correct order.

**Screenshots**
Restored: https://upload.metsh.tech/uN0rYI.png
OG: https://upload.metsh.tech/q3nJCS.png 

**Additional context**
None

**Comment by vertyco** [comment]
Fixed with v1.1.7
