### ISSUE TITLE
[LevelUp] `lvlset commandxp` is giving xp even when its disabled. + 2 Queries.

### ISSUE THREAD

**Issue by cool-aid-man** [vertyco/vrt-cogs#205]
Hi alex,
Hope you're doing well

I've got a few things to share today.
## 1st Issue
**Describe the bug**
What's the expected behavior of `lvlset commandxp`?
- If it's meant to give `xp` when you run the bot commands **(if enabled)** - then I think it's having some issues. 
- So, when it's **Disabled** - looks like it's still giving `xp` per command run. I've tried this with a test scenario which seems to be agreeing.

**Cog Version***
- Cog Version: `4.2.8`

**To Reproduce & Screenshot/Video**
- Steps to reproduce the behavior:
- Follow the video

https://github.com/user-attachments/assets/98019073-63b3-41ae-b5d0-b874f60c7931

**Expected behavior**
When `lvlset commandxp` is set to **Disabled** - It shouldn't give xp. 

----
## 2nd Query
- How does the cog decide how much `xp` should be given ‒ when the `xp` per message is set to the **default I.e.: `3- 6`**? - Is it completely random or something else is going on!
- Meaning ‒ say, if I send a BIG message with lots of formatting and emoji included - would it get the highest xp which is 6 in this case or would it get a randomized number!
- In my test scenario it looked like its random xp per message (correct me if I'm wrong here).
------------------
 - If it's randomized then - Is it possible for you to add a way where the bot could decide the xp by **judging** the `msg_content` as in - If the msg_content is big/better/well formatted or "good" then it'll incline towards the `highest xp` or give the highest xp?
 
 (not sure if it's a good idea though, since **spammers exist** & they'll find ways to get more `xp` but that's just a handful of users and it shouldn't be a problem to deal with them as you can **always** blacklist them anyways ― but the main issue might be knowing **which msg is a "good" msg** and which msg isn't aka "bad msg". Would it be too complex or doable ― I wanna know your point of view.)
 
 
 
 ----
 ## 3rd Query
 - Is it possible to make the levelup data available (just the ‒ user's `exp` & `weekly-exp` would suffice ) **via API** endpoint for other bots to hook into!! ― (like how [amari API](https://amaripy.readthedocs.io/en/latest/) works)
 - It'd be a **game changer** for development.
 - For example - we have a custom giveaway bot that uses the [**amari bot's API**](https://amaripy.readthedocs.io/en/latest/) to get the user's `amari_level` and `amari_weekly_exp `and then uses it as as `giveaway requirement` - so having that data available for this cog means HUGE deal ‒ and it **Not only** just for us but for other people to use the cog with their own bot.

**Comment by cool-aid-man** [comment]
Decided to edit and add an important 3rd Query instead of making a new issue.

**Comment by vertyco** [comment]
Your first query should be fixed now with **v4.2.13**

The 2nd and 3rd query are unrelated and need to be separate issues. The 2nd one is just a question and the answer is that it is random every time, if the xp is set to 3-6 then each valid message will get a random number from/including 3-6

The 3rd query would require a full rewrite so that probably wont happen within the next year at least.

**Comment by cool-aid-man** [comment]
Thanks 
And will do
