### ISSUE TITLE
[LvelUp] feature request: Rolling 30 day stats

### ISSUE THREAD

**Issue by MagicDanielle** [vertyco/vrt-cogs#208]
If possible it would be nice to ad a feature where levelup counts activity over the past rolling 30 days. Basically the same as the discord bot: statbot. I've been hunting for a cog with this feature for a long time. For example, I'd like to issue the server role "active" if someone has posted 200 messages within the past rolling 30 days, and gives the role inactive if they havent. They can also have the role if they've spent over 2 hours in specified voice channels within the past rolling 30 days. If they spend 2 hours in one of the voice channels on day 1 it gives them the active role. If they dont enter the voice channels again within the next 30 days it removes the role. This is different to having it check on a specified day each month. It's more dynamic.

**Comment by vertyco** [comment]
This would pretty much require a full rewrite as to do this would require every single message to be saved as its own entry with a timestamp attached to it, and every voice minute too. I have a plan to rewrite this cog in a little over a year, but even then i dont know if this is something i want to implement.
