### ISSUE TITLE
[Feature Request] [Support] Close ticket if no response from invoker

### ISSUE THREAD

**Issue by EternalllZM** [vertyco/vrt-cogs#21]
New configuration option similar to the one where it closes if the user leaves the guild. It should be a set timer once the ticket is open for them to say something (what they need) before it closes.

**Comment by vertyco** [comment]
This feature has been added as of now :)

**Comment by EternalllZM** [comment]
This should only look for the ticket invoker to send a message, instead of just anyone. Lots of support people go, "Do you need anything" thus "disabling" the close timer.

**Comment by vertyco** [comment]
It already does that.

**Comment by EternalllZM** [comment]
I will re-test. Maybe it was a fluke on my end.
