### ISSUE TITLE
[LevelUp] Unable to show Profile

### ISSUE THREAD

**Issue by TheOneMightyArc** [vertyco/vrt-cogs#210]
**Bug**
When executing [p]pf, some users are unable to generate their profile.

**Cog Version\***
Latest Version 4.1.1

**To Reproduce**
Brought cog data from older level up (3.X.X)

**Expected behavior**
Certain users encounter this error, and can not gain access to their profile.
**Screenshots**
Attached both log from levelup in server and in ssh.
![Screenshot 2024-10-11 184718](https://github.com/user-attachments/assets/6f23b912-6c1e-4bf5-93bd-9e0ea0e49539)
![Screenshot 2024-10-11 162557](https://github.com/user-attachments/assets/21c11a65-bb03-4e41-846f-d251593f3b71)

**Additional context**
Happens to some users, some do not have this issue. No discernable way to see without running command.

**Comment by vertyco** [comment]
Exception is now handled with v4.2.12, it will still log an error but will now tell you the username of the profile that failed so you can see which role icon is causing the issue.
