### ISSUE TITLE
[LevelUp] API endpoint exposing `userdata` (EXP, Levels etc) & other `essentials`.

### ISSUE THREAD

**Issue by cool-aid-man** [vertyco/vrt-cogs#211]
## Feature Request: API endpoint for `userdata`.
 Currently, the API supports image generation only and doesn’t provide essential **user data** like levels, weekly EXP, total EXP, or voice minutes, maybe leaderboard and other essentials.
 
 - Could you please consider adding an API endpoint that exposes `userdata`? (at minimum ‒ user's `level` & `weekly-exp` would suffice). Having access to this data via an API would be incredibly beneficial for bots to integrate with, similar to how the [Amari API](https://amaripy.readthedocs.io/en/latest/) works.
 
 - It'd be a **game changer** for development. 🙂
 - For instance, we have a custom giveaway bot that uses the [Amari API](https://amaripy.readthedocs.io/en/latest/) to fetch a user’s `amari_level` and `amari_weekly_exp` for giveaway requirements. If this cog could offer similar data, it would be a **huge** advantage, **Not** just for us but for anyone looking to integrate the cog into their own projects.
  
 
Additionally, I think it's worth mentioning that, since the `dashboard` cog is now available & being maintained, this could also help you facilitate the API by keeping the necessary components online. The dashboard framework could serve as a perfect foundation for integrating the new API endpoint.
​ 

I understand that implementing this would involve a significant rewrite of the cog, which takes time, and you’re likely be busy with other work as well. Still, we’d greatly **appreciate** it if you could consider `prioritizing` this enhancement when possible.
Now that the cog is gaining widespread adoption (that it deserves by all means 🙏), the potential for improvement is immense! 🙌

Thanks

**Comment by vertyco** [comment]
Asking me to prioritize a full rewrite so that specific functionality can be added that only you might use and sprinkling it with emojis, and word fluff comes across as very pompous and makes me not want to consider it.

IF I do rewrite LevelUp, it will be when I decide to do it and be appropriately prioritized with my other projects. I'm closing this and other issues that would require a rewrite.

**Comment by cool-aid-man** [comment]
Oh my god! I’m **genuinely** sorry that my request caused such response - I really didn’t intend for it to come across that way, **ever**. I’m not sure what else to say other than I truly apologize.
I only made the issue because you previously mentioned this would require a 'separate issue to be made', so I thought you were asking me to do so in order to keep track of things, like with your other cogs-issues.
I misunderstood the tone to take. 

And, I apologize for using the **wrong** term "prioritize" (& for adding emojis) and specifically sounding "pompous", (it really came from the place of how I consider writing IRL), **believe me** it was nowhere close to show-off or anything like that. Tho I did mention "..respecting your other work.." & "..when possible", but I can see how it didn’t come across as intended and that is on **me**.

You’re absolutely right - the request was specific to our needs (for now), and I fully **respect** that it’s up to you when, or if, you decide to do it.
Once again, I’m truly sorry if my words or approach made you feel bad. That was never my intention.

**Comment by vertyco** [comment]
Its all good, I was just being candid.
I don't speak for all developers of course, but generally feature requests are received best when they get straight to the point and include only necessary content. Basically you don't have to pitch it like a shark tank idea, but rather just state the feature, how it would work, and what it could be used for.
