### ISSUE TITLE
[LevelUp] Reaction stars are not counted by the cog

### ISSUE THREAD

**Issue by NoiselessVolatileLobster** [vertyco/vrt-cogs#214]
**Describe the bug**
I have noticed that levelup is not counting stars given to users when they react with a star emoji to their message. Giving stars using `[p]givestar` works as expected (They show up both with in `[p]startop` and `[p]profile`).
This appears to have broken after the LevelUp rewrite.

**Cog Version\***
4.2.16

**To Reproduce**

1. Type `[p]profile @username` and see number of stars.
2. React to one of that user's messages with a star emoji.
3. Type `[p]profile @username` again and see number is unchanged.

**Expected behavior**
The number of stars listed in `[p]startop` and `[p]profile` should increase when a message is reacted with a star emoji.

**Additional context**
Please note that the counter works when you run `[p]givestar`
I'm opening this issue after Vert confirmed this had not been added during the rewrite.

**Comment by vertyco** [comment]
This has been re-implemented now.
