### ISSUE TITLE
[assistant] feature request : Use free groq API instead of openai

### ISSUE THREAD

**Issue by Toasterme** [vertyco/vrt-cogs#217]
**Is your feature request related to a problem? Please describe.**
Groq API is free and it is a nice that way, you can choose a lot of model too

**Describe the solution you'd like**
Add the possibility to use another model, it can be groq, mistral, claude

**Describe alternatives you've considered**
Groq will be simple because it use the openai way

**Comment by vertyco** [comment]
I have no desire to add support for alternative endpoints or models  with Assistant. It is also not as simple as you think it is to add support for that.
