### ISSUE TITLE
[Bug] [Support] Designated ticket managers cannot add or remove people from tickets if they created it

### ISSUE THREAD

**Issue by EternalllZM** [vertyco/vrt-cogs#23]
I think those designated as ticket managers should be able to add/remove people from tickets they invoke, it doesn't make sense to hold them to the same permissions as regular members even if disabled.

**Comment by vertyco** [comment]
This is already a thing

**Comment by EternalllZM** [comment]
What am I missing then?

![Screenshot 2022-08-02 110430](https://user-images.githubusercontent.com/43221983/182420489-3996b488-b8ea-471e-b212-86e0f1c60037.png)
![Screenshot 2022-08-02 110420](https://user-images.githubusercontent.com/43221983/182420490-59b1e078-9dae-451d-97c5-9091d7172fdb.png)
![Screenshot 2022-08-02 110348](https://user-images.githubusercontent.com/43221983/182420492-b1fd40ce-c8d6-4667-a040-c1946dcc6ab4.png)

**Comment by vertyco** [comment]
oh i read what you were asking wrong, yes since it is "Your" ticket, it doesnt let you add anyone since the manage ticket perm is disabled, i'll adjust the logic to allow support roles to self manage tickets
