### ISSUE TITLE
[Support Cog] [Feature Request] multiple tickets please?

### ISSUE THREAD

**Issue by batman202012** [vertyco/vrt-cogs#24]
I would love to have multiple tickets, your cog is so good but only allows for one ticket panel. I have to use aaa3a's tickettool which is extremely bad compared to your cog. I prefer your cog so much, I even tried to close it and replace every instance of support with ticket just so I could have 2 copies.

**Comment by vertyco** [comment]
This feature is planned for September when red goes to 3.5, the  library we have to use currently is super buggy so ive been waiting for dpy2 to launch

**Comment by batman202012** [comment]
Awesome, I'd appreciate it.

**Comment by vertyco** [comment]
This feature has been implemented in my dpy2 branch of the cog(which you can use if you are on the dev version of red) and will be merged into main when red3.5 drops
