### ISSUE TITLE
[Feature Request] [LevelUp] Prestige XP conversion

### ISSUE THREAD

**Issue by EternalllZM** [vertyco/vrt-cogs#29]
Right now, if you prestige while being over the allowed prestige level. It will set you to prestige 1 level 1 zero experience. This feature request suggests that if you prestige while being over the minimum required level, all the extra experience past X level will be put towards your post-prestige level. This could be a toggle as well to preserve behavior others might prefer in this scenario.

Example: Level 40 is prestige requirement while member is level 43. All experience past level 40 would mean the user would most likely be Prestige 1 Level 12 after prestiging.

**Comment by vertyco** [comment]
Thats a good idea, i'll implement it in the next patch

**Comment by vertyco** [comment]
This feature has been implemented
