### ISSUE TITLE
[Feature Request] Cog: Support

### ISSUE THREAD

**Issue by batman202012** [vertyco/vrt-cogs#30]
I use support for verifying members in my server and mod related things, this usually requires uploading a id for verifying age and screenshots for mod stuff. Therefore it would be nice if support gave the ticket creator `attach_files` permissions. The ticket category has @everyone with those permissions but the ticket channels don't inherit them. I have implemented a patch on my bot but I do think that those permissions are kind of important for anyone using the tickets for these tasks.

**Comment by vertyco** [comment]
Just added this permission :)
