### ISSUE TITLE
[Feature Request][LevelUp] Command to reset XP and Stars only

### ISSUE THREAD

**Issue by cag1585** [vertyco/vrt-cogs#31]
I want to reset XP at years end and I see that guildreset resets the cog entirely in the guild forcing me to reset all other settings.
`levelset admin guildxpreset/globalxpreset` 

This would save all admin and user based settings and only reset XP points/level and stars

**Comment by vertyco** [comment]
This feature has been implemented in the latest update `[p]lset admin statreset`
