### ISSUE TITLE
[Feature Request][NoBot]Whitelist/blacklist per filter 

### ISSUE THREAD

**Issue by cag1585** [vertyco/vrt-cogs#32]
This would be handy. I can't run `errorlogs scroll` to view my console as it often deletes even though I'm only trying to target a log channel with the filter. 

Per filter would give better flexibility then per bot and I think would have more applications then just mine.

**Comment by vertyco** [comment]
This would require a schema change for the config. The cog was written to be a simple solution for cleaning content from other bots. You could also try changing the filter content for what youre trying to delete so that your errorlog messages dont get falsely flagged.

**Comment by cag1585** [comment]
Understood, thank you.
