### ISSUE TITLE
[Feature Request][NoNuke] New Action - Remove roles & add Mute

### ISSUE THREAD

**Issue by cag1585** [vertyco/vrt-cogs#33]
I think this leaves a safe alternative to kicks or bans.

**Comment by vertyco** [comment]
Reasonable, i have no eta for this FR but have plans to implement it

**Comment by vertyco** [comment]
Just pushed this feature with version 0.1.1
Action `strip` will strip all roles from the user that have elevated permissions, but still leave normal non-dangerous roles.
