### ISSUE TITLE
[Feature Request] [Tickets] Multiple panels on single message

### ISSUE THREAD

**Issue by EternalllZM** [vertyco/vrt-cogs#41]
It would be very useful if we could utilize a single message to host multiple different ticket panels/buttons that behave different.

This would allow members to select what type of ticket they are opening so it can be directed to the correct category/team for remediation immediately. Thank you for considering.

**Comment by vertyco** [comment]
![image](https://user-images.githubusercontent.com/58824393/205176539-4e6a46d5-4630-4c46-944d-59091be8f8c1.png)
![image](https://user-images.githubusercontent.com/58824393/205176567-a8b83434-0280-4cec-b67f-3e469ad4f751.png)

The cog will act as it does now, except now when adding a panel, you can specify a message that already has a button on it and that button will be added to it.
