### ISSUE TITLE
[Feature Request] [LevelUp] A command to repost the Top Weekly Exp Earners embed

### ISSUE THREAD

**Issue by cag1585** [vertyco/vrt-cogs#62]
A command similar to `lvltop` for the weekly winners. All it would need to do is re-post the same embed it post once a week.
This way users can pull it back up if they missed it.

**Comment by vertyco** [comment]
When the weekly stats reset, the previous weekly leaderboard is wiped. There is no practical way to save the embed. I can however add an option for members to be pinged
