### ISSUE TITLE
[Hunting] Bot doesn't respond to Bang

### ISSUE THREAD

**Issue by deXxterlab97** [vertyco/vrt-cogs#69]
**Describe the bug**
bot doesn't respond to bang

**Screenshots**
![bang](https://user-images.githubusercontent.com/31835797/218837432-768e63ed-d78c-4b98-b897-e5f5092fdb02.png)

![bang2](https://user-images.githubusercontent.com/31835797/218837665-8e6e56ca-6580-453d-b2a0-72b27517b88a.png)
![bang3](https://user-images.githubusercontent.com/31835797/218837770-26930003-7c32-4669-85f6-0b06a7c6c251.png)

**Additional context**
I've also reloaded the cog, doesn't help. I've checked with `hunting next` and it seems to correctly show when the new animal should appear.

Hunting version 3.2.11.
Ubuntu 22.04.1 LTS

**Comment by vertyco** [comment]
This should be fixed now with 3.2.12, ty for reporting
