### ISSUE TITLE
[Feature Request] [Tickets] Abilty to set title on Modals

### ISSUE THREAD

**Issue by PxlPioneer** [vertyco/vrt-cogs#79]
**Is your feature request related to a problem? Please describe.**
 It's a little annoying to see the `{NAME} Panel` in the title. The ability to change this would be handy

**Describe the solution you'd like**
The ability to set the title of the modals.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by PxlPioneer** [comment]
If this could be added relatively soon, I would be willing to drop a small donation :)

**Comment by vertyco** [comment]
Just pushed this feature :)
