### ISSUE TITLE
[Feature Request] [LevelUp] Implementation of an importer for user level data from Malarne's Leveler cog

### ISSUE THREAD

**Issue by dubsky0** [vertyco/vrt-cogs#87]

**Comment by vertyco** [comment]
This has been added with the latest update: `[p]lset admin importmalarne`

**Comment by dubsky0** [comment]
I cannot load Malarne to import the data. It is not updated for compatibility with 3.5+.
![image](https://github.com/vertyco/vrt-cogs/assets/25600193/e2fc242c-af8a-4e7c-94dc-5b6096ed251d)
