### ISSUE TITLE
[Tickets] Pin ticket answers/reason on open

### ISSUE THREAD

**Issue by EternalllZM** [vertyco/vrt-cogs#89]
**Is your feature request related to a problem? Please describe.**
Just QOL. Longer tickets can sometimes be a hassle figuring out what the original opening reason was for. Lots of scrolling to the top.

**Describe the solution you'd like**
`tickets` cog. When a ticket is opened, pin the embed containing answers to modals.

**Describe alternatives you've considered**
Forcing a poor mod to do it every time

**Additional context**
Nope - thanks

**Comment by vertyco** [comment]
This QoL feature has been implemented in Tickets v1.18.2, just pushed
