### ISSUE TITLE
[Levelup] Prestige Bug / Default no notifications request

### ISSUE THREAD

**Issue by theMisteryDE** [vertyco/vrt-cogs#92]
**Describe the bug**
I wanted to prestige the Oldies on my Server, since the Malarne Import seemed to have failed, even after telling me 10 profiles have been imported

And after installing the cog, I got the first puzzled reactions since it is auto active everywhere. Every of the 31 Servers the Bot is supporting :D
Would be nice if the Levelup Notification is default off.

**To Reproduce**
[p]lvlset prestige <user> <prestigelevel>

**Expected behavior**
Well yes, prestige level gets set

**Screenshots**

![image](https://github.com/vertyco/vrt-cogs/assets/44779420/c144cd8c-423f-496a-bc39-21e8879d788d)

**Additional context**

none

**Comment by vertyco** [comment]
The `setprestige` command should be fixed now, ty for reporting
