### ISSUE TITLE
[LevelUp] XP progress bar showing incorrect progress

### ISSUE THREAD

**Issue by karlsbjorn** [vertyco/vrt-cogs#94]
**Describe the bug**
When using `pf` the progress bar in both embed and image modes will always display at high percentages due to it calculating the difference in XP from level 1 to the next level, instead of from current level to next level.

**To Reproduce**
1. Use the `pf` command
2. Look at progress/xp bar

**Expected behavior**
The progress bar shows progress from current to next level

**Screenshots**
![image](https://github.com/vertyco/vrt-cogs/assets/40699625/f3389ec8-c276-4133-bb5f-593c11084afd)
![image](https://github.com/vertyco/vrt-cogs/assets/40699625/01dd8947-7f61-41e0-bf94-e3e127fd469c)
![DiscordCanary_G4EeawOYN7](https://github.com/vertyco/vrt-cogs/assets/40699625/b79e57de-5dd4-4eec-97cc-c6f84bba0f4c)

**Comment by vertyco** [comment]
This fix has been implemented, thanks for pointing it out!
