### ISSUE TITLE
[Feature Request] [LevelUp] How about MEE6, ProBot-style non-embed LevelUp notification?

### ISSUE THREAD

**Issue by ocformula** [vertyco/vrt-cogs#96]
**Is your feature request related to a problem? Please describe.**
The current embed notification doesn't seem to translate cleanly for languages like Korean and Japanese due to differences in word order.
For example, the expression "ocformula Just reached level 170 !" should be reworded to "ocformula 님, 방금 170 레벨에 도달했습니다!" when translated into Korean.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by vertyco** [comment]
Just pushed a change to the string that should make it easier to translate in crowdin, you can put the `{user}` and `{level}` arg anywhere you need
